#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/loadbalancer
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  tags: install

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
  tags: config

- name: Deploy load balancer config
  template:
    src: lb.conf.j2
    dest: /etc/nginx/sites-available/lb.conf
  notify: Restart nginx
  tags: config

- name: Enable load balancer site
  file:
    src: /etc/nginx/sites-available/lb.conf
    dest: /etc/nginx/sites-enabled/lb.conf
    state: link
  notify: Restart nginx
  tags: config

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
  tags: install