#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: install

- name: Deploy Nginx Configuration
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx
  tags: config

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true
  tags: install